### ISSUE TITLE
Dependencies causing errors after install

### ISSUE THREAD

**Issue by OliBridgman** [webfox/silverstripe-gallery#6]
Hey,

After installing the module I'm getting:

`Fatal error: Class 'GridFieldBulkUpload' not found` and `Fatal error: Class 'GridFieldSortableRows' not found`

Had a google and installing [GridFieldBulkEditingTools](https://github.com/colymba/GridFieldBulkEditingTools) and [https://github.com/UndefinedOffset/SortableGridField](https://github.com/UndefinedOffset/SortableGridField) fixed the issue. Dunno how dependencies work in composer so can't offer a solution to this.

Thanks

**Comment by hailwood** [comment]
Hey @OliBridgman,

Cheers for the bug report and you are correct that's the missing package.

With composer we simply need to add the additional dependency here: https://github.com/webfox/silverstripe-gallery/blob/master/composer.json#L12
Specifically `undefinedoffset/sortablegridfield` version `~0.6`

A pull request would be great if you have time. Otherwise I'll get to the update on Tuesday.

## 

Matt

**Comment by hailwood** [comment]
Released as 1.0.2
